apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: test-app-application
  namespace: argocd
spec:
  destination:
    namespace: test-app-ns
    name: in-cluster
  project: default
  source:
    path: .tekton
    repoURL: https://github.com/my-silly-organisation/test-app
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
